name = "ai-server"
main = "src/index.ts"
compatibility_date = "2025-04-08"

# Node.js 兼容性（如果你的 worker-adapter 用到 Node.js API）
compatibility_flags = ["nodejs_compat"]

# 本地开发端口（可选）
[dev]
port = 8080
local_protocol = "http"

[vars]
FRIDAY_API_KEY = "21902918114338451458"

# 暴露静态文件
#[site]
#bucket = "../client/dist"

# 私密环境变量通过 wrangler secret put 命令设置